language: generic
sudo: true
dist: trusty
before_install:
  - git clone https://github.com/uzzi1234/TestProject.git Scripts
  - chmod a+x ./Scripts/*.sh
install:
  - travis_retry ./Scripts/install.sh
  - ./Scripts/restructure-project.sh
script:
  - ./Scripts/build.sh && ./Scripts/run-tests.sh
after_success:
  - ./Scripts/notify-discord.sh